version: '3'
services: 
  web: 
    image: wordpress:latest
    ports: 
      - "8080:80"
    environment: 
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: Pa$$w0rd
      WORDPRESS_DB_USER: wordpress
    depends_on:
      - mysql

  mysql: 
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: wordpress 
      MYSQL_PASSWORD: Pa$$w0rd
      MYSQL_USER: wordpress
