apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      name: webserver
  template:
    metadata:
      labels:
        name: webserver
    spec:
      tolerations:
      - key: node-role.kubernetes.io/mater
        effect: NoSchedule
      containers:
      - name: nginx-webserver
        image: nginx